### PR TITLE
Significantly improve performance of row decoding. (#130)

### PR DESCRIPTION
**Pull request by tanner0101**
Moving https://github.com/vapor/postgresql/pull/130 here since GitHub is annoying and I can't merge changes into forks.

### CODE REVIEW

**Comment by tanner0101** [comment]
The expected should be `0.064`. So that's a 24% change, which is great! 

cc @MrMage 

@twof I think the problem here is that @vapor-bot only accepts merges into `master` as the new expected. We might need a way to declare branches like `1`, `3`, etc as "stable" branches or something.

**Comment by MrMage** [comment]
> The expected should be `0.064`. So that's a 24% change, which is great! cc @MrMage

👍 I guess with more complicated models it should be even better.

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1139 coins.

**Comment by tanner0101** [comment]
Definitely. @MrMage would you be interested in porting this to https://github.com/vapor/nio-postgres?

**Comment by MrMage** [comment]
@tanner0101 sure, but could you provide documentation on where I should add a benchmark test, and how I could run it? I'd like to have benchmarks in place before building this.

**Comment by tanner0101** [comment]
@MrMage sure thing:

There are a couple of performance tests here: https://github.com/vapor/nio-postgres/blob/master/Tests/NIOPostgresTests/NIOPostgresTests.swift#L264-L307

You can run those in Xcode normally, setting a baseline for your system first, then making changes and running again. Just be sure to change the Test scheme to build in release configuration.

To get a Postgres server running, you can use `docker-compose up psql-<version>`, i.e., `docker-compose up psql-11`. The docker containers are a bit slow though, so if you have postgres installed through something like homebrew that might be a better option. 

You can change the test credentials here: https://github.com/vapor/nio-postgres/blob/master/Tests/NIOPostgresTests/Utilities.swift#L4-L27. Just make sure to revert them before committing. The test credentials are meant to work w/ circle CI and the docker-compose file included w/ the project.

**Pull request merged**
